# Generated by Django 4.2.7 on 2023-11-24 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            ("AL", "Abelardo Luz "),
                            ("AR", "Araquari"),
                            ("BL", "Blumenau"),
                            ("BR", "Brusque"),
                            ("CA", "Camboriú"),
                            ("CO", "Concórdia"),
                            ("FR", "Fraiburgo "),
                            ("IB", "Ibirama"),
                            ("LU", "Luzerna"),
                            ("RS", "Rio do Sul "),
                            ("CA", "Camboriú"),
                            ("SR", "Santa Rosa do Sul"),
                            ("SB", "São Bento do Sul"),
                            ("SF", "São Francisco do Sul"),
                            ("SO", "Sombrio "),
                            ("VI", "Videira"),
                        ],
                        default="Null",
                        max_length=2,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("members", models.ManyToManyField(related_name="equipes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
