# Generated by Django 4.2.7 on 2023-11-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="data_final",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="data_inicio",
            field=models.DateField(null=True),
        ),
    ]
