# Generated by Django 4.2.7 on 2023-11-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("core", "0002_user_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="fotos",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
