# Generated by Django 4.2.7 on 2023-11-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_avaliacao_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.IntegerField(
                choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")], default="Null"
            ),
        ),
    ]
