# Generated by Django 4.2.7 on 2023-11-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_hackathon_fotos"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="turma",
            field=models.CharField(default="3infos", max_length=100),
            preserve_default=False,
        ),
    ]
