# Generated by Django 4.2.7 on 2023-11-24 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_avaliacao_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipe",
            name="avaliacao",
        ),
    ]
