# Generated by Django 4.2.7 on 2023-11-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_equipe_user_equipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="members",
            field=models.ManyToManyField(related_name="equipes", to="core.user_equipe"),
        ),
    ]
