# Generated by Django 4.2.7 on 2023-11-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_hackathon_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="tech",
            field=models.CharField(default="Python", max_length=500),
            preserve_default=False,
        ),
    ]
