# Generated by Django 4.2.7 on 2023-11-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_equipe_avaliacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="nota",
            field=models.IntegerField(
                choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")], default="Null"
            ),
        ),
    ]
