# Generated by Django 4.2.7 on 2023-11-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_equipe_tech"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.IntegerField(default=90000, max_length=100),
            preserve_default=False,
        ),
    ]
