# Generated by Django 4.2.7 on 2023-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_equipe_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="members",
            field=models.ManyToManyField(related_name="equipes", to="core.user_equipe"),
        ),
    ]
