# Generated by Django 4.2.7 on 2023-11-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_user_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telefone",
            field=models.CharField(max_length=30),
        ),
    ]
