# Generated by Django 4.2.7 on 2023-11-24 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_equipe_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="members",
            field=models.ManyToManyField(related_name="equipes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="User_Equipe",
        ),
    ]
