# Generated by Django 4.2.7 on 2023-11-24 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_equipe_members_delete_user_equipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipe",
            name="description",
        ),
    ]
