# Generated by Django 4.2.7 on 2023-11-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_equipe_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tema", models.CharField(max_length=255)),
                ("ano", models.DateField(null=True)),
                (
                    "campus",
                    models.IntegerField(
                        choices=[
                            (1, "Abelardo Luz"),
                            (2, "Araquari"),
                            (3, "Blumenau"),
                            (4, "Brusque"),
                            (5, "Camboriú"),
                            (6, "Concórdia"),
                            (7, "Fraiburgo "),
                            (8, "Ibirama"),
                            (9, "Luzerna"),
                            (10, "Rio do Sul"),
                            (11, "Santa Rosa do Sul"),
                            (12, "São Bento do Sul"),
                            (13, "São Francisco do Sul"),
                            (14, "Sombrio "),
                            (15, "Videira"),
                        ]
                    ),
                ),
                ("estado", models.IntegerField(choices=[(1, "Pendente"), (2, "Em Andamento"), (3, "Concluído")])),
                ("data_inicio", models.DateTimeField(null=True)),
                ("data_final", models.DateTimeField(null=True)),
            ],
        ),
    ]
