# Generated by Django 4.2.7 on 2023-11-25 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_curriculo_lattes_user_formacao_user_telefone"),
        ("core", "0009_categoria"),
    ]

    operations = []
