# Generated by Django 4.2.7 on 2023-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_merge_20231125_0126"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="hackathon",
            name="tema",
        ),
        migrations.AddField(
            model_name="hackathon",
            name="tema",
            field=models.ManyToManyField(related_name="hackathons", to="core.tema"),
        ),
    ]
